<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="SPMGetContractLines"
                  targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/http/SPM/MISIMDOMNotifySPM/SPMGetContractLines"
                  xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/http/SPM/MISIMDOMNotifySPM/SPMGetContractLines"
                  xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                  xmlns:msg_in_out="http://www.openbravo.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <plt:partnerLinkType name="Request_Response_plt">
        <plt:role name="Request-Response_role">
            <plt:portType name="tns:Request_Response_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.openbravo.com" schemaLocation="xsd/SPMGetContractLines.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="Openbravo_msg_in">
        <wsdl:part name="Openbravo" element="msg_in_out:Openbravo"/>
    </wsdl:message>
    <wsdl:message name="Openbravo_msg_out">
        <wsdl:part name="Openbravo" element="msg_in_out:Openbravo"/>
    </wsdl:message>
    <wsdl:portType name="Request_Response_ptt">
        <wsdl:operation name="Request-Response">
            <wsdl:input message="tns:Openbravo_msg_in"/>
            <wsdl:output message="tns:Openbravo_msg_out"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
